### PR TITLE
Fixed #171 – Updated Doorhanger Dismissal Text 

### LINKED ISSUE #171: Add support for Normandy Add-on Study
Add-on studies don't use pref flips to enable the add-on

### PR DESCRIPTION
**Pull request by maxxcrawford**
I was having issues rebase'ing `pontoon` to `master`. I merged `pontoon` with the latest `master`, and will squash the commits once approved to minimize the noise. 

**Languages**: 

- [x] de
- [x] en_CA
- [x] en_GB
- [x] en_US
- [x] es_ES
- [x] es_MX
- [x] fr
- [x] it
- [x] ru
- [x] zh_CN

### CODE REVIEW

**Comment by maxxcrawford** [comment]
@flodolo Should I leave this PR open while the string gets localized?

**Comment by flodolo** [comment]
> @flodolo Should I leave this PR open while the string gets localized?

I don't know, I have no clue what the expectations are in terms of shipping, deadlines, etc. (and there's an ongoing email thread about it).

**Comment by maxxcrawford** [comment]
@flodolo Understood. I'm going to leave this open until I hear back more on those points from @wthayer. Thanks!

**Comment by wthayer** [comment]
We need this update prior to the ramp up, which I don't expect to begin until at least mid-Dec, so the deadline is Dec 10.

**Comment by maxxcrawford** [comment]
Added language checklist for progress on this!

**Pull request merged**
